from my_space_view import MySpaceView
from my_files_view import MyFilesView
from my_adobe_connect_recording_view import MyAdobeConnectRecordingView
from my_wims_exercices_view import MyWimsExercicesView
from my_external_resources_view import MyExternalResourcesView
from my_glossary_terms_view import MyGlossaryTermsView
from my_pod_videos_view import MyPodVideosView
from my_courses_view import MyCoursesView
